version: "3.9"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - db-data:/usr/src/app/data
      - uploads-data:/usr/src/app/uploads
    restart: unless-stopped

volumes:
  db-data:
  uploads-data:
